#!/usr/bin/env bash
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Paper-style PPO training configuration.
export NUM_EPOCHS="${NUM_EPOCHS:-600}"
export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-480}"
export NUM_MINIBATCHES="${NUM_MINIBATCHES:-4}"
export PPO_UPDATE_EPOCHS="${PPO_UPDATE_EPOCHS:-4}"

# Keep the flat action head tractable while retaining exact boundary slots.
export GRID_RESOLUTION="${GRID_RESOLUTION:-auto}"
export MAX_AUTO_GRID_RESOLUTION="${MAX_AUTO_GRID_RESOLUTION:-100}"
export EXACT_ACTION_SLOTS="${EXACT_ACTION_SLOTS:-50000}"

# Score = w1 * chiplet area + w2 * incident pin count.
export PLACEMENT_AREA_WEIGHT="${PLACEMENT_AREA_WEIGHT:-1.0}"
export PLACEMENT_PIN_WEIGHT="${PLACEMENT_PIN_WEIGHT:-1.0}"

# Thermal tables are always checked/generated by train.py. Leave this at 0 to
# reuse valid existing tables; set FORCE_THERMAL_TABLES=1 only to rebuild them.
export FORCE_THERMAL_TABLES="${FORCE_THERMAL_TABLES:-0}"

# The delegated runner passes --no_checkpoint explicitly. Logs, metrics and
# best-layout JSON/PNG files are still retained for every case.
export RUN_PREFIX="${RUN_PREFIX:-all_examples_600epochs_$(date +%Y%m%d_%H%M%S)}"

exec bash "${SCRIPT_DIR}/test_all_examples_2epochs.sh"
